spring:
  datasource:
    url: &url jdbc:postgresql://localhost:5432/electronic_realty_database
    driver-class-name: org.postgresql.Driver
    username: &username postgres
    password: &password 1234
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.yandex.ru
    port: 587
    username: tester17591@yandex.ru
    password: kpnhdfzjtsrcbews
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:db/migration
    schemas: test
    enabled: true
    user: *username
    password: *password
    url: *url
  thymeleaf:
    prefix: classpath:/views/templates/
default:
  image:
    path: ${user.dir}/src/main/resources/realty/static
    links: >
      https://raw.githubusercontent.com/lynxofficial/electronic_realty/main/images/firstImage.png,
      https://raw.githubusercontent.com/lynxofficial/electronic_realty/main/images/secondImage.jpg,
      https://raw.githubusercontent.com/lynxofficial/electronic_realty/main/images/thirdImage.png,
      https://raw.githubusercontent.com/lynxofficial/electronic_realty/main/images/fourthImage.jpg, 
      https://raw.githubusercontent.com/lynxofficial/electronic_realty/main/images/fifthImage.png
