server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: test
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    baseline-on-migrate: true
    fail-on-missing-locations: true
    locations: classpath:db/migration
    schemas: test
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
  thymeleaf:
    prefix: classpath:/views/templates/
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      timeout: 2000
      repositories:
        enabled: false
  cache:
    redis:
      time-to-live: 10000
default:
  image:
    path: ${user.dir}/src/main/resources/realty/static
    links: >
      https://raw.githubusercontent.com/lynxofficial/electronic_realty/main/images/firstImage.png,
      https://raw.githubusercontent.com/lynxofficial/electronic_realty/main/images/secondImage.jpg,
      https://raw.githubusercontent.com/lynxofficial/electronic_realty/main/images/thirdImage.png,
      https://raw.githubusercontent.com/lynxofficial/electronic_realty/main/images/fourthImage.jpg, 
      https://raw.githubusercontent.com/lynxofficial/electronic_realty/main/images/fifthImage.png
